#######################################
#     Author: Boris Zhenikhov         #
#     Email: znhv@yandex.com          #
#######################################


name: build

on:
  - push

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Linting
        run: |
          python -m pip install --upgrade pip
                    pip install poetry
                    make install
  # Тесты должны выполняться при каждом запуске workflow
  test:
    needs: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install

      - name: Test
        run: make test

      - name: test
        run: |
          make test

      - name: Publish test code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: dade0d4f9d431c5e34d8bca9ad909ae6b4c8fadf38df7d15aee55b2e28eb968f